### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by mat41997** [Redrield/TalkingBot#5]
logs
`[m[0;31;1m|@|[0;37;22m QiiQii[m [0;37;1m? QiiQii[m`

config
```
miscellaneous:
  QiiQii:
  - 'QiiQii jest teraz bardzo zajety '
```

timings
https://timings.aikar.co/v2/?id=e2fa2c77cda449e19f234d8a7447065b

ss
![1](https://cloud.githubusercontent.com/assets/5884000/16249820/f86107fc-3818-11e6-9e36-01ef8db1efd6.png)

**Comment by Redrield** [comment]
You're going to need to provide me more information than that. Could you give me any errors that popped up?

**Comment by mat41997** [comment]
i no have any error

full logs
http://pastebin.com/mkYMeeu2

**Comment by Redrield** [comment]
The version works fine on my server. Keep in mind that running the plugin on an offline mode server may cause undocumented behaviour
